### ISSUE TITLE
How to adapt template when your SAN has 2 EQL_IDs and names 

### ISSUE THREAD

**Issue by mikefarace** [asosso/zbx3-dell-equallogic#3]
When I run the snmpwalk command below, I get back 2 results for the ID and name.
nmpwalk -v2c -c public "EqualLogic IP" .1.3.6.1.4.1.12740.2.1.1.1.9.1

iso.3.6.1.4.1.12740.2.1.1.1.9.1.385156503 = STRING: "EQ1-JUMBO"
iso.3.6.1.4.1.12740.2.1.1.1.9.1.1049520707 = STRING: "EQ2-FAST"

I tried to copy the tempalte, and in the copy change the values to be EQL_ID2 and EQL_NAME2, and link both templates to the same host, but that just blew up, so I'm only using the first one for now.

Suggestions to adapt for this configuration?  thanks!

**Comment by asosso** [comment]
Hi @mikefarace ,

Could you clone the host instead the template?  
You could change the **Macro** for each host in: `Host > Equallogic Jumbo > Macro `

Equallogic Jumbo example: 

```
{$EQL_ID} => 385156503 
{$EQL_NAME} => EQ1-JUMBO
```

Equallogic Fast example: 

```
{$EQL_ID} => 1049520707 
{$EQL_NAME} => EQ2-FAST
```

Let me know

**Comment by mikefarace** [comment]
I didn't know I could clone a host and leave it as an entry with the same IP address, but ya, I will give that a try and just call the host name EqualLogic-Jumbo and EqualLogic-Fast. Will confirm if that works.  

Thanks!
